# Generated by Django 2.2 on 2020-01-22 08:03

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvimport', '0003_auto_20200122_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvimport',
            name='delimiter',
            field=models.CharField(default=';', max_length=10),
        ),
        migrations.AlterField(
            model_name='csvimport',
            name='model_name',
            field=models.CharField(default='IS_app.Group4TransactionalData', help_text='Please specify the app_label.model_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='csvimport',
            name='upload_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='D:\\Universidad\\Alemania\\Information Systems\\IS_Project\\infosys-project\\django-project\\media'), upload_to='csv'),
        ),
        migrations.AlterField(
            model_name='importmodel',
            name='csvimport',
            field=models.ForeignKey(on_delete=True, to='csvimport.CSVImport'),
        ),
    ]
